<a href="https://colab.research.google.com/github/guilpassos/Data_Science/blob/main/Atividade_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#Módulo 3 - Introdução à Data Science e Machine Learning
#1- Import o Numpy
import numpy as np


In [3]:
#2 - Utilize a função range do python para criar automaticamente uma lista de
#números variando de 0 até 15.
l1 = list(range(16))
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [11]:
#3 - Converta a lista criada para um objeto do tipo numpy array.
m1 = np.array(range(16))
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
#4 - Crie um novo array equivalente ao anterior utilizando diretamente os
#recursos do numpy.
m1 = np.arange(16)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
#5 - Crie um array de 10 zeros
a1 = np.zeros(10)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
#6 - Crie um array de 10 números "um".
a2 = np.ones(10)
a2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
#7 - Crie um array de 10 números "5"
a3 = np.ones(10) * 5
a3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [22]:
#8 - Crie um array de inteiros de 10 até 50
a4 = np.arange(10, 51)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [24]:
#9 - Crie uma matriz identidade 3x3
a5 = np.diag(np.array([1, 1, 1]))
a5

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])