<a href="https://colab.research.google.com/github/guilpassos/Data_Science/blob/main/Treinando_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#IMPORTANDO A BIBLIOTECA NUMPY
import numpy as np

In [4]:
dados = np.random.rand(2, 3)

In [5]:
dados

array([[0.19586632, 0.69326374, 0.57321694],
       [0.46505057, 0.45228609, 0.64549996]])

In [6]:
dados.dtype

dtype('float64')

In [7]:
dados.shape

(2, 3)

In [8]:
dados.ndim

2

In [9]:
lista = (1, 5, 5.3, 6, 1.25)

In [10]:
dados2 = np.array(lista)
dados2

array([1.  , 5.  , 5.3 , 6.  , 1.25])

In [11]:
lista2 = [[1, 2, 3, 4], [4, 3, 2, 1]]

In [12]:
dados3 = np.array(lista2)
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [13]:
dadoszeros = np.zeros(10)
dadoszeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
dadoszeros2 = np.zeros((2, 3))
dadoszeros2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
dadosum = np.ones(5)
dadosum

array([1., 1., 1., 1., 1.])

In [17]:
dadosseq = np.arange(10)

In [18]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
dadosseq2 = np.arange(0, 10, 2)
dadosseq2

array([0, 2, 4, 6, 8])

In [20]:
dadosseq.dtype

dtype('int64')

In [21]:
dadosseqf = dadosseq.astype(np.float64)
dadosseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
dados4 = np.array([[1, 2, 3], [3, 2, 1]])
dados4

array([[1, 2, 3],
       [3, 2, 1]])

In [23]:
dados4 * dados4

array([[1, 4, 9],
       [9, 4, 1]])

In [24]:
dados4 - dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.33333333, 0.5       , 1.        ]])

In [28]:
dados5 = dados4 + dados4
dados5

array([[2, 4, 6],
       [6, 4, 2]])

In [29]:
dados5>dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

In [30]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
dadosseq[3:6]

array([3, 4, 5])

In [33]:
dadosseq[3:6] = 20
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [34]:
fatiadados = dadosseq[2:4]
fatiadados

array([ 2, 20])

In [35]:
fatiadados[1] = 2000
fatiadados

array([   2, 2000])

In [36]:
dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [37]:
fatiadados[:] = 333
fatiadados

array([333, 333])

In [38]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

In [39]:
fatia2 = dadosseq[2:4].copy()
fatia2

array([333, 333])

In [40]:
fatia2[:] = 111
fatia2

array([111, 111])

In [41]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

In [43]:
dados6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
dados6[1, 2]

6

In [47]:
mascara = (dadosseq<100)

In [48]:
mascara

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
dadosseq[dadosseq<20] = 888

In [50]:
dadosseq

array([888, 888, 333, 333,  20,  20, 888, 888, 888, 888])

In [51]:
dados7 = np.arange(15).reshape((3, 5))

In [52]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [54]:
np.dot(dados7.T, dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])